apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }} # add this line for static node port on our environment
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
